### ISSUE TITLE
Cannot fetch the data of product, ID: "xxxx"

### ISSUE THREAD

**Issue by Covernel** [kitce/viurr#7]
Is it broken or something changed on viu side? It's work before (a few days ago).

```
> viurr inspect episode 6979
Cannot fetch the data of product, ID: "6979"

> viurr inspect episode 294960
Cannot fetch the data of product, ID: "294960"
````

Tried on windows and ubuntu w/ HK IP (Video is not blocked via Browser)

**Comment by ayija** [comment]
> Is it broken or something changed on viu side? It's work before (a few days ago).
> 
> ```
> > viurr inspect episode 6979
> Cannot fetch the data of product, ID: "6979"

I can still use the `inspect` command but not the `download` anymore

**Comment by kitce** [comment]
Please upgrade to 1.2.1

**Comment by Covernel** [comment]
Thanks so much for the fix. It works now
